### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by AnkoGo123** [crlf0710/charlesmine-rs#1]
how to run ?
how to run ?

**Comment by crlf0710** [comment]
If you're a rust user. Just execute `cargo install --git https://github.com/crlf0710/charlesmine-rs`, this will build and install a `charlesmine.exe` to `.cargo/bin/"

Then you can execute `charlesmine` within Command Prompt (cmd.exe) to execute the game.

If you're not, you'll need to install rust first to build and get the `charlesmine.exe` program. You can then copy the program and use it elsewhere.

**Comment by AnkoGo123** [comment]
thanks



---Original---
From: "Charles ***@***.***&gt;
Date: Sun, Oct 10, 2021 14:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [crlf0710/charlesmine-rs] how to run ? (#1)




 
If you're a rust user. Just execute cargo install --git https://github.com/crlf0710/charlesmine-rs, this will build and install a charlesmine.exe to `.cargo/bin/"
 
Then you can execute charlesmine within Command Prompt (cmd.exe) to execute the game.
 
If you're not, you'll need to install rust first to build and get the charlesmine.exe program. You can then copy the program and use it elsewhere.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
